MENU_ITEMS = [
    {"item_id": "DOSA_001", "text": "Plain Dosa", "category": "DOSA", "price": "6.99", "type": "Veg"},
    {"item_id": "DOSA_002", "text": "Onion Chilli Dosa", "category": "DOSA", "price": "9.99", "type": "Veg"},
    {"item_id": "DOSA_003", "text": "Masala Dosa", "category": "DOSA", "price": "9.99", "type": "Veg"},
    {"item_id": "DOSA_004", "text": "Mysore Masala Dosa", "category": "DOSA", "price": "9.99", "type": "Veg"},
    {"item_id": "DOSA_005", "text": "Ghee Roast Crepe", "category": "DOSA", "price": "10.99", "type": "Veg"},
    {"item_id": "DOSA_006", "text": "Paper Roast Crepe", "category": "DOSA", "price": "10.99", "type": "Veg"},
    {"item_id": "DOSA_007", "text": "Cheese Dosa", "category": "DOSA", "price": "9.99", "type": "Veg"},
    {"item_id": "DOSA_008", "text": "Gunpowder Dosa", "category": "DOSA", "price": "10.99", "type": "Veg"},
    {"item_id": "DOSA_009", "text": "Maligai Gunpowder Rava Dosa", "category": "DOSA", "price": "12.99", "type": "Veg"},
    {"item_id": "DOSA_010", "text": "Chettinad Dosa", "category": "DOSA", "price": "10.99", "type": "Veg"},
    {"item_id": "DOSA_011", "text": "Andhra Dosa", "category": "DOSA", "price": "9.99", "type": "Veg"},
    {"item_id": "DOSA_012", "text": "Paneer Dosa", "category": "DOSA", "price": "10.99", "type": "Veg"},
    {"item_id": "DOSA_013", "text": "Egg Dosa", "category": "DOSA", "price": "10.99", "type": "Egg"},
    {"item_id": "DOSA_014", "text": "Chicken Tikka Dosa", "category": "DOSA", "price": "11.99", "type": "Non-Veg"},
    {"item_id": "DOSA_015", "text": "Goat Kheema Dosa", "category": "DOSA", "price": "12.99", "type": "Non-Veg"},
    {"item_id": "DOSA_016", "text": "Rava Dosa", "category": "DOSA", "price": "9.99", "type": "Veg"},
    {"item_id": "DOSA_017", "text": "Onion Rava Dosa", "category": "DOSA", "price": "10.99", "type": "Veg"},
    {"item_id": "DOSA_018", "text": "Masala Rava Dosa", "category": "DOSA", "price": "11.99", "type": "Veg"},
    {"item_id": "UTTA_001", "text": "Uttapam Thick Pancake", "category": "UTTAPAM", "price": "7.99", "type": "Veg"},
    {"item_id": "UTTA_002", "text": "Onion Chilli Uttapam", "category": "UTTAPAM", "price": "10.99", "type": "Veg"},
    {"item_id": "UTTA_003", "text": "Gunpowder Uttapam", "category": "UTTAPAM", "price": "9.99", "type": "Veg"},
    {"item_id": "UTTA_004", "text": "Ghee Uttapam", "category": "UTTAPAM", "price": "9.99", "type": "Veg"},
    {"item_id": "UTTA_005", "text": "Mix Veg Uttapam", "category": "UTTAPAM", "price": "10.99", "type": "Veg"},
    {"item_id": "BRED_001", "text": "Plain Naan", "category": "BREADS", "price": "1.99", "type": "Veg"},
    {"item_id": "BRED_002", "text": "Butter Naan", "category": "BREADS", "price": "2.49", "type": "Veg"},
    {"item_id": "BRED_003", "text": "Garlic Naan", "category": "BREADS", "price": "2.99", "type": "Veg"},
    {"item_id": "BRED_004", "text": "Onion Kulcha", "category": "BREADS", "price": "3.49", "type": "Veg"},
    {"item_id": "BRED_005", "text": "Paratha", "category": "BREADS", "price": "3.99", "type": "Veg"},
    {"item_id": "BRED_006", "text": "Chefs Special Naan", "category": "BREADS", "price": "3.99", "type": "Veg"},
    {"item_id": "BRED_007", "text": "Mutton Kheema Naan", "category": "BREADS", "price": "4.99", "type": "Non-Veg"},
    {"item_id": "KEBA_001", "text": "Paneer Tikka Kebab", "category": "KEBABS", "price": "12.99", "type": "Veg"},
    {"item_id": "KEBA_002", "text": "Hara Bhara Kebab", "category": "KEBABS", "price": "12.99", "type": "Veg"},
    {"item_id": "KEBA_003", "text": "Veg Seekh Kebab", "category": "KEBABS", "price": "12.99", "type": "Veg"},
    {"item_id": "KEBA_004", "text": "Tandoori Chicken King of Kebabs", "category": "KEBABS", "price": "12.99", "type": "Non-Veg"},
    {"item_id": "KEBA_005", "text": "Chicken Chapli Kebab", "category": "KEBABS", "price": "13.99", "type": "Non-Veg"},
    {"item_id": "KEBA_006", "text": "Chicken Tikka Kebab", "category": "KEBABS", "price": "14.99", "type": "Non-Veg"},
    {"item_id": "KEBA_007", "text": "Chicken Hariyali Kebab", "category": "KEBABS", "price": "14.99", "type": "Non-Veg"},
    {"item_id": "KEBA_008", "text": "Tangdi Kebab", "category": "KEBABS", "price": "12.99", "type": "Non-Veg"},
    {"item_id": "KEBA_009", "text": "Reshmi Kebab", "category": "KEBABS", "price": "15.49", "type": "Non-Veg"},
    {"item_id": "KEBA_010", "text": "Murg Malai Kebab(chicken)", "category": "KEBABS", "price": "14.99", "type": "Non-Veg"},
    {"item_id": "KEBA_011", "text": "Sheesh Kebab", "category": "KEBABS", "price": "16.99", "type": "Non-Veg"},
    {"item_id": "KEBA_012", "text": "Boti Kebab", "category": "KEBABS", "price": "16.99", "type": "Non-Veg"},
    {"item_id": "KEBA_013", "text": "Kebab e Juglbandi", "category": "KEBABS", "price": "19.99", "type": "Non-Veg"},
    {"item_id": "KEBA_014", "text": "Tandoori Pomfret Fish", "category": "KEBABS", "price": "19.99", "type": "Non-Veg"},
    {"item_id": "KEBA_015", "text": "Lamb Chops (6)", "category": "KEBABS", "price": "22.99", "type": "Non-Veg"},
    {"item_id": "ICVG_001", "text": "Gobi Manchurian (Gravy)", "category": "INDO-CHINESE (VEG)", "price": "11.99", "type": "Veg"},
    {"item_id": "ICVG_002", "text": "Veg Manchurian (Gravy)", "category": "INDO-CHINESE (VEG)", "price": "10.99", "type": "Veg"},
    {"item_id": "ICVG_003", "text": "Chilli Gobi (Gravy)", "category": "INDO-CHINESE (VEG)", "price": "10.99", "type": "Veg"},
    {"item_id": "ICVG_004", "text": "Vegetable Fried Rice", "category": "INDO-CHINESE (VEG)", "price": "10.99", "type": "Veg"},
    {"item_id": "ICVG_005", "text": "Schezwan Veg Fried Rice", "category": "INDO-CHINESE (VEG)", "price": "11.99", "type": "Veg"},
    {"item_id": "ICVG_006", "text": "Veg Hakka Noodles", "category": "INDO-CHINESE (VEG)", "price": "10.99", "type": "Veg"},
    {"item_id": "ICVG_007", "text": "Schezwan Veg Hakka Noodles", "category": "INDO-CHINESE (VEG)", "price": "11.99", "type": "Veg"},
    {"item_id": "ICNV_001", "text": "Chicken Manchurian Gravy", "category": "INDO-CHINESE (NON-VEG / EGG)", "price": "12.99", "type": "Non-Veg"},
    {"item_id": "ICNV_002", "text": "Chilli Chicken Gravy", "category": "INDO-CHINESE (NON-VEG / EGG)", "price": "12.99", "type": "Non-Veg"},
    {"item_id": "ICNV_003", "text": "Schezwan Chicken Gravy", "category": "INDO-CHINESE (NON-VEG / EGG)", "price": "12.99", "type": "Non-Veg"},
    {"item_id": "ICNV_004", "text": "Schezwan Shrimp", "category": "INDO-CHINESE (NON-VEG / EGG)", "price": "13.99", "type": "Non-Veg"},
    {"item_id": "ICNV_005", "text": "Fried Rice Egg/Chicken", "category": "INDO-CHINESE (NON-VEG / EGG)", "price": "11.99", "type": "Egg"},
    {"item_id": "ICNV_006", "text": "Schezwan Fried Rice Egg/Chicken", "category": "INDO-CHINESE (NON-VEG / EGG)", "price": "12.99", "type": "Egg"},
    {"item_id": "ICNV_007", "text": "Hakka Fried Rice Egg/Chicken", "category": "INDO-CHINESE (NON-VEG / EGG)", "price": "11.99", "type": "Egg"},
    {"item_id": "VSTR_001", "text": "Veg Spring Rolls", "category": "VEG STARTERS", "price": "7.99", "type": "Veg"},
    {"item_id": "VSTR_002", "text": "Samosa", "category": "VEG STARTERS", "price": "7.99", "type": "Veg"},
    {"item_id": "VSTR_003", "text": "Corn Chat", "category": "VEG STARTERS", "price": "12.99", "type": "Veg"},
    {"item_id": "VSTR_004", "text": "Gobi Manchurian", "category": "VEG STARTERS", "price": "12.99", "type": "Veg"},
    {"item_id": "VSTR_005", "text": "Gobi 65", "category": "VEG STARTERS", "price": "12.99", "type": "Veg"},
    {"item_id": "VSTR_006", "text": "Paneer Pakora", "category": "VEG STARTERS", "price": "13.99", "type": "Veg"},
    {"item_id": "VSTR_007", "text": "Paneer Manchurian", "category": "VEG STARTERS", "price": "13.99", "type": "Veg"},
    {"item_id": "VSTR_008", "text": "Chilli Paneer", "category": "VEG STARTERS", "price": "13.99", "type": "Veg"},
    {"item_id": "VSTR_009", "text": "Baby Corn Manchurian", "category": "VEG STARTERS", "price": "12.99", "type": "Veg"},
    {"item_id": "VSTR_010", "text": "Mushroom Majestic", "category": "VEG STARTERS", "price": "12.99", "type": "Veg"},
    {"item_id": "BIRY_001", "text": "Boneless Mutton Fry Dum Biryani", "category": "BIRYANI", "price": "17.99", "type": "Non-Veg"},
    {"item_id": "BIRY_002", "text": "Nattukadi Dum Biryani(chicken)", "category": "BIRYANI", "price": "17.99", "type": "Non-Veg"},
    {"item_id": "BIRY_003", "text": "Ulavacharu Biryani Chicken/Goat/Egg", "category": "BIRYANI", "price": "14.99", "type": "Egg"},
    {"item_id": "BIRY_004", "text": "Ulavacharu Biryani Shrimp or Fish", "category": "BIRYANI", "price": "14.99", "type": "Non-Veg"},
    {"item_id": "VCUR_001", "text": "Tomato Dhal", "category": "VEG CURRIES", "price": "12.99", "type": "Veg"},
    {"item_id": "VCUR_002", "text": "Palak Dhal", "category": "VEG CURRIES", "price": "12.99", "type": "Veg"},
    {"item_id": "VCUR_003", "text": "Methi Ka Saalan", "category": "VEG CURRIES", "price": "12.99", "type": "Veg"},
    {"item_id": "VCUR_004", "text": "Vegetable Korma", "category": "VEG CURRIES", "price": "12.99", "type": "Veg"},
    {"item_id": "VCUR_005", "text": "Channa Masala", "category": "VEG CURRIES", "price": "12.99", "type": "Veg"},
    {"item_id": "VCUR_006", "text": "Aloo Palak", "category": "VEG CURRIES", "price": "12.99", "type": "Veg"},
    {"item_id": "VCUR_007", "text": "Paneer Butter Masala", "category": "VEG CURRIES", "price": "13.99", "type": "Veg"},
    {"item_id": "VCUR_008", "text": "Paneer Tikka Masala", "category": "VEG CURRIES", "price": "13.99", "type": "Veg"},
    {"item_id": "CHKN_001", "text": "Butter Chicken", "category": "CHICKEN CURRIES", "price": "16.99", "type": "Non-Veg"},
    {"item_id": "CHKN_002", "text": "Chicken Tikka Masala", "category": "CHICKEN CURRIES", "price": "16.99", "type": "Non-Veg"},
    {"item_id": "CHKN_003", "text": "Andhra Chicken Curry", "category": "CHICKEN CURRIES", "price": "14.99", "type": "Non-Veg"},
    {"item_id": "CHKN_004", "text": "Chettinad Chicken", "category": "CHICKEN CURRIES", "price": "14.99", "type": "Non-Veg"},
    {"item_id": "GOAT_001", "text": "Goat Mughlai", "category": "GOAT CURRIES", "price": "17.99", "type": "Non-Veg"},
    {"item_id": "GOAT_002", "text": "Gongura Mutton", "category": "GOAT CURRIES", "price": "19.99", "type": "Non-Veg"},
    {"item_id": "GOAT_003", "text": "Hyderabadi Mutton Masala", "category": "GOAT CURRIES", "price": "16.99", "type": "Non-Veg"},
    {"item_id": "GOAT_004", "text": "Mutton Sukka", "category": "GOAT CURRIES", "price": "17.99", "type": "Non-Veg"},
    {"item_id": "GOAT_005", "text": "Shahi Gosht Korma", "category": "GOAT CURRIES", "price": "17.99", "type": "Non-Veg"},
    {"item_id": "SEA_001", "text": "Andhra Fish Pulusu", "category": "SEAFOOD CURRIES", "price": "17.99", "type": "Non-Veg"},
    {"item_id": "SEA_002", "text": "Nellore Fish Curry", "category": "SEAFOOD CURRIES", "price": "17.99", "type": "Non-Veg"},
    {"item_id": "SEA_003", "text": "Kadi Shrimp", "category": "SEAFOOD CURRIES", "price": "17.99", "type": "Non-Veg"},
    {"item_id": "SEA_004", "text": "Shrimp Tikka Masala", "category": "SEAFOOD CURRIES", "price": "17.99", "type": "Non-Veg"},
    {"item_id": "SEA_005", "text": "Crab Pepper Masala", "category": "SEAFOOD CURRIES", "price": "21.99", "type": "Non-Veg"},
    {"item_id": "DESS_001", "text": "Qubani ka Meetha", "category": "DESSERTS", "price": "5.99", "type": "Veg"},
    {"item_id": "DESS_002", "text": "Shahi Tukda", "category": "DESSERTS", "price": "5.99", "type": "Veg"},
    {"item_id": "DESS_003", "text": "Badam Halwa", "category": "DESSERTS", "price": "7.99", "type": "Veg"},
    {"item_id": "DESS_004", "text": "Mango Kesari", "category": "DESSERTS", "price": "3.99", "type": "Veg"},
    {"item_id": "DESS_005", "text": "Gulab Jamun", "category": "DESSERTS", "price": "3.99", "type": "Veg"},
    {"item_id": "DESS_006", "text": "Ice Cream Vanilla/Strawberry/Mango", "category": "DESSERTS", "price": "4.49", "type": "Veg"},
    {"item_id": "DESS_007", "text": "Night Kulfi", "category": "DESSERTS", "price": "4.49", "type": "Veg"},
    {"item_id": "DCOL_001", "text": "Soft Drinks", "category": "DRINKS (COLD)", "price": "1.99", "type": "Veg"},
    {"item_id": "DCOL_002", "text": "House Milk Shakes", "category": "DRINKS (COLD)", "price": "4.99", "type": "Veg"},
    {"item_id": "DCOL_003", "text": "Mango Lassi", "category": "DRINKS (COLD)", "price": "3.99", "type": "Veg"},
    {"item_id": "DCOL_004", "text": "Masala Butter Milk", "category": "DRINKS (COLD)", "price": "2.50", "type": "Veg"},
    {"item_id": "DCOL_005", "text": "Plain Buttermilk", "category": "DRINKS (COLD)", "price": "1.99", "type": "Veg"},
    {"item_id": "DCOL_006", "text": "Nimbu Soda", "category": "DRINKS (COLD)", "price": "2.50", "type": "Veg"},
    {"item_id": "DCOL_007", "text": "Rose Sherbet", "category": "DRINKS (COLD)", "price": "3.49", "type": "Veg"},
    {"item_id": "DHOT_001", "text": "Chai", "category": "DRINKS (HOT)", "price": "2.50", "type": "Veg"},
    {"item_id": "DHOT_002", "text": "South Indian Coffee", "category": "DRINKS (HOT)", "price": "2.50", "type": "Veg"},
    {"item_id": "DHOT_003", "text": "Madras Filter Coffee", "category": "DRINKS (HOT)", "price": "3.99", "type": "Veg"},
    {"item_id": "FANV_001", "text": "Hyderabadi Chicken 65", "category": "FRY APPETIZERS (NON-VEG)", "price": "13.99", "type": "Non-Veg"},
    {"item_id": "FANV_002", "text": "Chicken Chilli", "category": "FRY APPETIZERS (NON-VEG)", "price": "13.99", "type": "Non-Veg"},
    {"item_id": "FANV_003", "text": "Chicken Manchurian Batter", "category": "FRY APPETIZERS (NON-VEG)", "price": "13.99", "type": "Non-Veg"},
    {"item_id": "FANV_004", "text": "Chicken 65 Boneless", "category": "FRY APPETIZERS (NON-VEG)", "price": "13.99", "type": "Non-Veg"},
    {"item_id": "FANV_005", "text": "Ginger Chicken", "category": "FRY APPETIZERS (NON-VEG)", "price": "13.99", "type": "Non-Veg"},
    {"item_id": "FANV_006", "text": "Garlic Chicken", "category": "FRY APPETIZERS (NON-VEG)", "price": "13.99", "type": "Non-Veg"},
    {"item_id": "FANV_007", "text": "Pepper Chicken Fry", "category": "FRY APPETIZERS (NON-VEG)", "price": "13.99", "type": "Non-Veg"},
    {"item_id": "FANV_008", "text": "Chicken Lollipop", "category": "FRY APPETIZERS (NON-VEG)", "price": "13.99", "type": "Non-Veg"},
    {"item_id": "FANV_009", "text": "Chicken Majestic", "category": "FRY APPETIZERS (NON-VEG)", "price": "13.99", "type": "Non-Veg"},
    {"item_id": "FANV_010", "text": "Cilantro Chicken", "category": "FRY APPETIZERS (NON-VEG)", "price": "13.99", "type": "Non-Veg"},
    {"item_id": "FANV_011", "text": "Karivepaku Chicken Fry", "category": "FRY APPETIZERS (NON-VEG)", "price": "14.99", "type": "Non-Veg"},
    {"item_id": "FANV_012", "text": "Chilli Chicken 65", "category": "FRY APPETIZERS (NON-VEG)", "price": "14.99", "type": "Non-Veg"},
    {"item_id": "SFRY_001", "text": "Fish 65", "category": "SEAFOOD FRY", "price": "16.99", "type": "Non-Veg"},
    {"item_id": "SFRY_002", "text": "Malabar Fish Fry", "category": "SEAFOOD FRY", "price": "17.99", "type": "Non-Veg"},
    {"item_id": "SFRY_003", "text": "Chilli Fish", "category": "SEAFOOD FRY", "price": "16.99", "type": "Non-Veg"},
    {"item_id": "SFRY_004", "text": "Andhra Fish Fry", "category": "SEAFOOD FRY", "price": "16.99", "type": "Non-Veg"},
    {"item_id": "SFRY_005", "text": "Grill Bone In Fish", "category": "SEAFOOD FRY", "price": "19.99", "type": "Non-Veg"},
    {"item_id": "SCRB_001", "text": "Shrimp Fry", "category": "SHRIMP & CRAB", "price": "17.99", "type": "Non-Veg"},
    {"item_id": "SCRB_002", "text": "Shrimp Majestic", "category": "SHRIMP & CRAB", "price": "17.99", "type": "Non-Veg"},
    {"item_id": "SCRB_003", "text": "Hyderabadi Shrimp 65", "category": "SHRIMP & CRAB", "price": "17.99", "type": "Non-Veg"},
    {"item_id": "SCRB_004", "text": "Gongura Shrimp", "category": "SHRIMP & CRAB", "price": "18.99", "type": "Non-Veg"},
    {"item_id": "SCRB_005", "text": "Chilli Shrimp", "category": "SHRIMP & CRAB", "price": "18.99", "type": "Non-Veg"},
    {"item_id": "SCRB_006", "text": "Crab Pepper Roast", "category": "SHRIMP & CRAB", "price": "21.99", "type": "Non-Veg"},
    {"item_id": "EGGD_001", "text": "Egg Masala Fry", "category": "EGG DISHES", "price": "10.99", "type": "Egg"},
    {"item_id": "EGGD_002", "text": "Egg Omelette", "category": "EGG DISHES", "price": "9.99", "type": "Egg"},
    {"item_id": "EGGD_003", "text": "Chicken Omelette", "category": "EGG DISHES", "price": "12.99", "type": "Egg"},
    {"item_id": "EGGD_004", "text": "Egg Bhurji", "category": "EGG DISHES", "price": "10.99", "type": "Egg"},
]
